name: SpringUp with Rabih
favicon: null
layout_spectrum: 0.40257749636657536
typography_spectrum: 0.5501434558536857
title: SpringUp with Rabih
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14181941584683955
  lightness: 0.07915170374326408
  saturation: 0.06554229464381933
  rhythmicContrast: 0.6448637794237584
purpose: []
